- hosts: ubuntu
  gather_facts: yes
  sudo: yes
  vars:
    ssl_certificate_hostname_fqdn: 192.168.33.2.xip.io
    subversion_base_dir: /data/svn
    subversion_parent_path: "{{ subversion_base_dir }}/repos"
    subversion_auth_user_file: "{{ subversion_base_dir }}/.svnpasswd"
    subversion_user_passwords:
      - { user: hnakamur, password: hogehoge }
    ruby_version: 2.1.3
    redmine_auth_user_file: "{{ subversion_auth_user_file }}"
  roles:
    - hostname
    - vagrant_user_locale
    - resolvconf
    - apt_sources
    - apt_update
    - base_packages
    - ntp
    - sysstat
    - ssl_certificate
    - ruby
    - app_user
    - apache
    - subversion
    - role: svn_repo
      svn_repo_name: test
    - postgresql
    - role: monit
      monit_check_interval_seconds: 20
      monit_check_interval_comment: 20-second intervals
    - redmine
